micronaut:
  application:
    name: beceps
  server:
    port: ${SERVICE_PORT:8080}
    cors:
      enabled: true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  security:
    enabled: true
    intercept-url-map:
      - pattern: /swagger/**
        http-method: GET
        access:
          - isAnonymous()
      - pattern: /swagger-ui/**
        http-method: GET
        access:
          - isAnonymous()
    token:
      basic-auth:
        enabled: false
      jwt:
        enabled: true
        generator:
          access-token-expiration: 3600
        signatures:
          secret:
            generator:
              secret: ${JWT_SECRET:becepsgymtoolforvamkuniversitysecret}s
              jws-algorithm: HS256
datasources:
  default:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3308/beceps}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:zaq1@WSX}
    driverClassName: com.mysql.cj.jdbc.Driver
    schema-generate: NONE
    dialect: MYSQL
jackson:
  serialization:
    failOnEmptyBeans: false
    writeDatesAsTimestamps: true
endpoints:
  health:
    enabled: true
    sensitive: false
