micronaut:
  application:
    name: beceps
  server:
    port: ${SERVICE_PORT:8080}
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  security:
    enabled: true
    intercept-url-map:
      - pattern: /swagger/**
        http-method: GET
        access:
          - isAnonymous()
      - pattern: /swagger-ui/**
        http-method: GET
        access:
          - isAnonymous()
    token:
      basic-auth:
        enabled: false
      jwt:
        enabled: true
        generator:
          access-token-expiration: 3600
        signatures:
          secret:
            generator:
              secret: becepsgymtoolforvamkuniversitysecret
              jws-algorithm: HS256
datasources:
  default:
    url: jdbc:mysql://localhost:3308/beceps
    username: root
    password: zaq1@WSX
    driverClassName: com.mysql.cj.jdbc.Driver
jpa:
  default:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        hbm2ddl:
          auto: validate
#        show_sql: true
jackson:
  serialization:
    failOnEmptyBeans: false
    writeDatesAsTimestamps: true
endpoints:
  health:
    enabled: true
    sensitive: false
